
Cosmetics:
  TestItem:                       # Name of cosmetic
    modelID: 1                    # customModelData
    lore: ["Test Item", "wow! lore!", "so cool"]           # Lore to display
    material: PAPER               #Material, recommended: PAPER, must be all uppercase
    type: HAT                     # Types: INVENTORY_ITEM, HAT, CHESTPLATE, LEGGINGS, BOOTS
