
Cosmetics:
  TestItem:                       # Internal name of cosmetic, must not have a space
    name: lol                     # Visual name of cosmetic, displayed to the player
    modelID: 1                    # customModelData
    lore: ["Test Item", "wow! lore!", "so cool"]           # Lore to display
    material: PAPER               #Material, recommended: PAPER | https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    type: HAT                     # Must be all Upper-case, Types: INVENTORY_ITEM, HAT, CHESTPLATE, LEGGINGS, BOOTS
