name: Cosmetics
version: ${project.version}
main: com.ilm9001.cosmetics.Cosmetics
api-version: 1.17
depend: [ eco ]
authors: [ ilm9001 ]
description: Cosmetics plugin for Dreamland
website: ilm9001.com
